export const SET_COMPANIES_DATA = 'SET_COMPANIES_DATA';
export const SET_RADIO_ACTIVE = 'SET_RADIO_ACTIVE';
export const SET_STORAGE_VALUE = 'SET_STORAGE_VALUE';
export const SET_TRANSFER_VALUE = 'SET_TRANSFER_VALUE';
